name: PR test

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'

jobs:
  tests:
    if: |
      !(github.event_name == 'pull_request' && github.event.pull_request.merged == true)

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run tests
        run: |
          echo "tests run"

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build 
        run: |
          echo "Build"          
