name: PR test

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '**'

jobs:
  tests:
    if: github.ref_name != 'develop' &&  github.ref_name != 'master' && (!contains(github.head_commit.message, 'Merge')) || (github.ref_name == 'develop' && github.actor != 'hk1313')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run tests
        run: |
          echo "tests run"
          echo "${GITHUB_CONTEXT}"
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}

  build:
    runs-on: ubuntu-latest
    if: ${{ github.actor != 'hk1313' }}
    steps:
      - uses: actions/checkout@v3

      - name: Build 
        run: |
          echo "Build"
          echo "${GITHUB_CONTEXT}"
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
