name: PR test

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '**'

jobs:
  tests:
    if: ((!contains(github.event.head_commit.message, 'Merge')) && github.ref_name != 'develop') || ((!contains(github.event.head_commit.message, 'Merge')) && github.ref_name != 'master')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run tests
        run: |
          echo "tests run"
          echo "${GITHUB_CONTEXT}"
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build 
        run: |
          echo "Build"
          echo "${GITHUB_CONTEXT}"
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}