name: PR test

on:
  push:
    branches:
      - '*'
      - '!master'
      - '!develop'
    tags-ignore:
      - '**'
  pull_request:
    types: [closed]

jobs:
  tests:
    runs-on: ubuntu-latest
    if: github.base_ref != 'develop' && github.base_ref != 'master' && github.head_ref != 'develop' && github.head_ref != 'master'
    steps:
      - uses: actions/checkout@v3

      - name: Run tests
        run: |
          echo "tests run"
          echo "${GITHUB_CONTEXT}"
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}

  build:
    runs-on: ubuntu-latest
    if: github.head_ref != 'develop' && github.head_ref != 'master'
    steps:
      - uses: actions/checkout@v3

      - name: Build 
        run: |
          echo "Build"
          echo "${GITHUB_CONTEXT}"
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}